#!/bin/sh -e

mkdir -p "$1/usr/share/man/man3"
for manpage in gl4
do
	(
		cd "$manpage"
		for file in *.xml
		do
			echo "$file"
			xsltproc --xinclude --noout --nonet /usr/share/xml/docbook/xsl-stylesheets-*/manpages/docbook.xsl "$file"
		done
		install -m644 *.3G "$1/usr/share/man/man3/"
	)
done
