#!/bin/sh -e
# I can't get the assembler to run with --32, so assembly components are disabled (-DUSE_GAS)

CC="$CC -m32"
CXX="$CXX -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig
export LD_LIBRARY_PATH=/usr/lib32

wayland="$(kiss l wayland 2>/dev/null)" || :
[ "$wayland" ] && wayland=ON || wayland=OFF

cmake \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_INSTALL_LIBDIR=lib32 \
	-DBUILD_WSI_WAYLAND_SUPPORT=$wayland \
	-DUSE_GAS=OFF

make
make install

rm -rf "$1/usr/share" "$1/etc" "$1/usr/bin" "$1/${XDG_DATA_HOME:-"$HOME/.local/share"}"
rm -rf "$1/usr/share" "$1/usr/include" "$1/usr/bin" "$1/etc" "$1/${XDG_DATA_HOME:-"$HOME/.local/share"}"
