#!/bin/sh -e
CC="$CC -m32"
CXX="$CXX -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig
export LD_LIBRARY_PATH=/usr/lib32

meson build \
	--libdir /usr/lib32 \
	-Dprefix=/usr \
	-Dlocalstatedir=/var \
	-Dsysconfdir=/etc \
	-Ddatabase=simple \
	-Dtests=false \
	-Ddoxygen=false \
	-Dopenssl=disabled \
	-Dman=false

# We disable the manpages, as they require a perl module.
meson compile -Cbuild
meson install -Cbuild

[ -d "$1/usr/lib32/pkgconfig" ] && for i in "$1/usr/lib32/pkgconfig/"*
do
	sed 's_/lib_/lib32_g' $i > _
	mv _ $i
done

rm -rf "$1/usr/share" "$1/etc" "$1/usr/bin" "$1/usr/include/"
