#!/bin/sh -e

cmake . -Bbuild \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_BUILD_TYPE=None \
	-DCMAKE_SKIP_INSTALL_RPATH=ON \
	-DGRAPHITE2_COMPARE_RENDERER=OFF \
	-DGRAPHITE2_VM_TYPE=direct

cmake --build build
cmake --install build
