#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -Wno-dev -G Ninja

ninja -C build
ninja -C build install

# remove cmake files
rm -rf "$1/usr/share/eigen3/cmake"
