#!/bin/sh -e

cmake -DCMAKE_INSTALL_PREFIX=/usr
make
make install

# install runit service
mkdir -p "$DESTDIR/etc/sv/xsettingsd"
cp files/run "$DESTDIR/etc/sv/xsettingsd/run"

# clean up
rm -r "$DESTDIR/usr/lib/systemd"
