#!/bin/sh -e

cat > makeinfo <<EOF
#!/bin/sh
printf 'makeinfo (GNU texinfo) 5.2\n'
EOF

chmod +x makeinfo
export PATH=$PATH:$PWD

./configure \
	--prefix=/usr \
	--with-lib-path=/usr/lib:/usr/local/lib \
	--enable-targets=x86_64-linux-gnu \
	--enable-deterministic-archives \
	--enable-install-libiberty \
	--disable-gold \
	--enable-lto \
	--enable-ld=default \
	--enable-plugins \
	--disable-werror \
	--disable-gdb \
	--disable-nls \
	--disable-readline \
	--with-mmap \
	--with-system-zlib

make configure-host
make tooldir=/usr
make tooldir=/usr install

ln -sf ld.bfd "$1/usr/bin/ld"
