#!/bin/sh -e

for patch in patches/*.patch ; do
    patch -p1 < $patch
done

cmake \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE='None' \
    -Wno-dev \
    -Bbuild \
    -S .

make -C build
make -C build install
