#!/bin/sh -e
CC="$CC -m32"
CXX="$CXX -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig
export LD_LIBRARY_PATH=/usr/lib32

patch -p1 < no-bash.patch

mk() {
    make \
        GOLANG=no \
        CC="$CC" \
        PREFIX=/usr \
        SBINDIR=/usr/bin \
        LIBDIR=/usr/lib32 \
        PKGCONFIGDIR=/usr/lib32/pkgconfig \
        RAISE_SETFCAP=no \
        INDENT=" " \
        "$@"
}

mk
mk DESTDIR="$1" install
# [ -d "$1/usr/lib32/pkgconfig" ] && for i in "$1/usr/lib32/pkgconfig/"*
# do
# 	sed 's_/lib_/lib32_g' $i > _
# 	mv _ $i
# done
rm -rf "$1/usr/share" "$1/etc" "$1/usr/bin" "$1/${XDG_DATA_HOME:-"$HOME/.local/share"}"
find "$1/usr/include/" -iname "*.h" -not -name "*x86*" -exec rm -f {} \;
