#!/bin/sh -e

meson \
	--prefix=/usr \
	--sysconfdir=/etc \
	--mandir=/usr/share/man \
	--localstatedir=/var \
	--buildtype=plain \
	-Dintrospection=enabled \
	-Dpackage-origin="https://kisslinux.org" \
	-Dpackage-name="GStreamer bad plug-ins (KISS Linux)" \
	. output

ninja -C output
ninja -C output install
