#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --mandir=/usr/share/man \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --disable-nls \
    --enable-daemon \
    --enable-utp \
    --without-systemd-daemon \
    --without-gtk

make
make install

mkdir -p "$1/etc/sv/transmission"
cp run "$1/etc/sv/transmission/"
