#!/bin/sh -e

./configure \
    --target=arm-none-eabi \
    --prefix=/usr \
    --enable-newlib-io-long-long \
    --enable-newlib-io-c99-formats \
    --enable-newlib-register-fini \
    --enable-newlib-retargetable-locking \
    --disable-newlib-supplied-syscalls \
    --disable-nls

make

mkdir -p "$DESTDIR"/usr/arm-none-eabi/lib

make install
