#!/bin/sh -e

meson \
	--prefix=/usr \
	-Ddep11=true \
	-Dbuilder=true \
	-Drpm=false \
	-Dalpm=false \
	-Dfonts=true \
	-Dstemmer=false \
	-Dman=false \
	-Dgtk-doc=false \
	-Dintrospection=true \
	. output

ninja -C output
ninja -C output install
