#!/bin/sh -e
CC="$CC -m32"
CXX="$CXX -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig
export LD_LIBRARY_PATH=/usr/lib32

export CFLAGS="$CFLAGS -I/usr/include/drm"

./configure \
	--prefix=/usr \
	--libdir=/usr/lib32

make
make DESTDIR="$1" install

rm -rf "$1/usr/include" "$1/usr/share" "$1/usr/bin"
