#!/bin/sh -e
CC="$CC -m32"
CXX="$CXX -m32"
export PKG_CONFIG_PATH=/usr/lib32/pkgconfig
export LD_LIBRARY_PATH=/usr/lib32

./configure \
	--prefix=/usr \
	--libdir=/usr/lib32 \
	--sysconfdir=/etc \
	--disable-a52 \
	--disable-lavrate \
	--disable-maemo-plugin

make
make install
[ -d "$1/usr/lib32/pkgconfig" ] && for i in "$1/usr/lib32/pkgconfig/"*
do
	sed 's_/lib_/lib32_g' $i > _
	mv _ $i
done
rm -rf "$1/usr/share" "$1/etc" "$1/usr/bin"
