#!/bin/sh -e

./configure \
	--prefix=/usr \
	--disable-java \
	--disable-native-java \
	--disable-csharp \
	--disable-libasprintf \
	--enable-threads=posix \
	--disable-rpath \
	--without-emacs \
	--disable-acl \
	--with-included-glib \
	--with-included-libcroco \
	--without-git \
	--with-included-libxml \
	--with-included-libunistring \
	--disable-openmp \
	--disable-curses \
	--without-examples \
	--enable-nls

make
make install

# strip out libtextstyle cos libtextstyle is in a different package
# (gettext won't build unless libtextstyle is already installed \
#  and libtextstyle gets installed into destdir where gettext can't \
#  find it)
rm "$1"/usr/share/info/libtextstyle.info
rm -r "$1"/usr/share/doc/libtextstyle
rm "$1"/usr/lib/libtextstyle.*
rm -r "$1"/usr/include/textstyle*
