#!/bin/sh -e

# Use lib not lib64 by default.
sed '/m64=/s/lib64/lib/' gcc/config/i386/t-linux64 > _
mv -f _ gcc/config/i386/t-linux64
sed 's/lib64/lib/' gcc/config/i386/linux64.h > _
mv -f _ gcc/config/i386/linux64.h

# Build must happen outside of gcc source.
mkdir -p gcc-build
cd gcc-build

# Grab the system's GCC version.
IFS=. read -r gcc_version _ 2>/dev/null \
    < "$KISS_ROOT/var/db/kiss/installed/gcc/version" || gcc_version=null

# Skip the bootstrap process if we are able.
#case $2 in "$gcc_version"*)
#    printf '%s\n' "Minor version difference, disabling bootstrap."
#    bootstrap=--disable-bootstrap
#esac

../configure \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --disable-symvers \
    --disable-libmpx \
    --disable-libmudflap \
    --disable-libsanitizer \
    --disable-install-libiberty \
    --disable-libssp \
    --disable-werror \
    --disable-fixed-point \
    --disable-libstdcxx-pch \
    --disable-nls \
    --disable-__cxa_atexit \
    --disable-linker-build-id \
    --disable-libunwind-excepions \
    --enable-checking=release \
    --enable-default-pie \
    --enable-shared \
    --enable-threads \
    --enable-tls \
    --enable-languages=c,c++ \
    --without-included-gettext \
    --with-zstd=no \
    --with-system-zlib \
    --target=avr \
    --with-as=/usr/bin/avr-as \
    --with-ld=/usr/bin/avr-ld \
    --disable-bootstrap

make
make DESTDIR="$1" install

# Save 35MB.
find "$1" -name libgtkpeer.a  -exec rm -f {} +
find "$1" -name libgjsmalsa.a -exec rm -f {} +
find "$1" -name libgij.a      -exec rm -f {} +

rm -r "$DESTDIR"/usr/share/man/man7
rm "$DESTDIR"/usr/lib/libcc1.*
