#!/bin/sh -e

# Doesn't compile without remove these flags as of 4.10
export CFLAGS="${CFLAGS/-fno-plt/}"
export CXXFLAGS="${CXXFLAGS/-fno-plt/}"
export LDFLAGS="${LDFLAGS/,-z,now/}"
# MingW Wine builds fail with relro
export LDFLAGS="${LDFLAGS/,-z,relro/}"

export CFLAGS="$CFLAGS -mno-avx2 -mfpmath=sse -fwrapv -fno-strict-aliasing -gdwarf-2 -gstrict-dwarf"
export CXXFLAGS="$CXXFLAGS -mno-avx2 -mfpmath=sse -fwrapv -fno-strict-aliasing -gdwarf-2 -gstrict-dwarf -std=c++17"

mkdir -p build32 build64

( # 64bit build
	cd build64
	../proton-wine/configure \
		--prefix=/usr \
		--libdir=/usr/lib \
		--with-x \
		--disable-tests \
		--enable-win64
	make
)

( # 32bit build+install
	cd build32
	export PKG_CONFIG_PATH=/usr/lib32/pkgconfig
	export LD_LIBRARY_PATH=/usr/lib32
	../proton-wine/configure \
		--prefix=/usr \
		--libdir=/usr/lib32 \
		--with-x \
		--disable-tests \
		--with-win64=../build64
	make
	make \
		prefix=/usr \
		libdir=/usr/lib32 \
		dlldir=/usr/lib32/wine install
)

( # 64bit install
	cd build64
	make \
		prefix=/usr \
		libdir=/usr/lib \
		dlldir=/usr/lib/wine install
)

# Fix font aliasing for win32 programs
mkdir -p "$1/usr/share/fontconfig/conf.avail" "$1/usr/share/fontconfig/conf.default"
cp 30-win32-aliases.conf "$1/usr/share/fontconfig/conf.avail/30-win32-aliases.conf"
ln -s ../conf.avail/30-win32-aliases.conf "$1/usr/share/fontconfig/conf.default/30-win32-aliases.conf"
