#!/bin/sh -e

make amalg
make install PREFIX=/usr

# Create these symlinks ourselves as luajit relies
# on ldconfig to do so and musl does not provide it.
# Commented as I use glibc
#ln -s libluajit-5.1.so.2.0.5 "$1/usr/lib/libluajit-5.1.so"
#ln -s libluajit-5.1.so.2.0.5 "$1/usr/lib/libluajit-5.1.so.2"
