#!/bin/sh -e
CC="$CC -m32"
CXX="$CXX -m32"
export PKG_CONFIG_LIBDIR=/usr/lib32/pkgconfig # don't let pkgconf find 64bit gtk+3
export LD_LIBRARY_PATH=/usr/lib32

meson \
	--prefix=/usr \
	--libdir=/usr/lib32 \
	--sysconfdir=/etc \
	--mandir=/usr/share/man \
	--localstatedir=/var \
	--buildtype=plain \
	-Dalsa=enabled \
	-Dintrospection=disabled \
	-Dpackage-origin="https://k1ss.org" \
	-Dpackage-name="GStreamer base plug-ins (KISS Linux)" \
	-Dgtk_doc=disabled \
	. output

ninja -C output
ninja -C output install

rm -rf "$1/usr/bin" "$1/usr/include" "$1/usr/share"
