#!/bin/sh -e

sed 's|//\(#define MBEDTLS_THREADING_C\)|\1|' include/mbedtls/config.h > _
mv _ include/mbedtls/config.h
sed 's|//\(#define MBEDTLS_THREADING_PTHREAD\)|\1|' include/mbedtls/config.h > _
mv _ include/mbedtls/config.h

mkdir build
cd build

cmake .. \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DENABLE_TESTING=OFF \
	-DUSE_SHARED_MBEDTLS_LIBRARY=ON \
	-DCMAKE_BUILD_TYPE=Release

cmake --build .
cmake --install .
