#!/bin/sh -e

# The provided built script is impressively non-standard
# Maintenance being a nightmare is the price I pay ig
# Here's a complete reimplementation

mkdir -p "$DESTDIR/usr/bin" "$DESTDIR/usr/share/uxn"

CFLAGS="$CFLAGS -std=c89 -Wall -Wno-unknown-pragmas"

LDFLAGS="-L/usr/lib $(sdl2-config --cflags --libs)"

$CC $CFLAGS src/uxnasm.c \
	-o "$DESTDIR/usr/bin/uxnasm"
$CC $CFLAGS src/uxn.c \
	src/devices/system.c \
	src/devices/file.c \
	src/devices/datetime.c \
	src/devices/mouse.c \
	src/devices/controller.c \
	src/devices/screen.c \
	src/devices/audio.c \
	src/uxnemu.c \
	$LDFLAGS \
	-o "$DESTDIR/usr/bin/uxnemu"
$CC $CFLAGS src/uxn.c \
	src/devices/system.c \
	src/devices/file.c \
	src/devices/datetime.c \
	src/uxncli.c \
	-o "$DESTDIR/usr/bin/uxncli"

for file in $(find projects -type f -iname "*.tal")
do
	"$DESTDIR/usr/bin/uxnasm" "$file" "${file%.*}.rom" || true
done

cp -r etc projects "$DESTDIR/usr/share/uxn/"
