#!/bin/sh -e

meson build \
	-Dprefix=/usr \
	-Dlocalstatedir=/var \
	-Dsysconfdir=/etc \
	-Ddatabase=simple \
	-Dtests=false \
	-Ddoxygen=false \
	-Dopenssl=disabled \
	-Dman=false

# We disable the manpages, as they require a perl module.
meson compile -Cbuild
meson install -Cbuild

mkdir -p "$1/etc/sv/pulseaudio"
cp run "$1/etc/sv/pulseaudio/"
