#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_TESTING=NO \
    -DWITH_WAYLAND=OFF \
    -DWITH_X11=ON \
    -Wno-dev -G Ninja

ninja -C build
ninja -C build install
