#!/bin/sh

user="$(cat /etc/jackuser)"

prlimit --rtprio=95 --memlock=unlimited -p $$
exec su "${user:-"nobody"}" -c "librespot \
    --name "Librespot" \
    --bitrate 320 \
    --initial-volume 100 \
    --backend jackaudio \
    --format S32"
